### ISSUE TITLE
Minimal sites notice

### ISSUE THREAD

**Issue by caesar** [garritfra/darktheme.club#27]
The PR template asks contributors to agree to the following:

> ***I confirm that I have read the [FAQ section](https://darktheme.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

However, https://darktheme.club/faq only has one red section, and doesn't mention minimal sites.
I suspect this is copied from the PR template for 512kb.club which does have a notice about minimal sites.

If the intention is not to allow minimal sites on darktheme.club, the appropriate notice should be added to the FAQ.
Alternatively, the warning should be removed from the PR template.

**Comment by garritfra** [comment]
Hi, I'm glad you catched this!
You're right, this has been copied from 512kb.club by mistake. I don't think we should care about how minimal a site is, since it's not a criteria for the "leaderboard". I'd suggest to remove that notice entirely.

Do you have time to fix this? Otherwise, I'll fix it later today.

**Comment by caesar** [comment]
Sure, I'll get to it shortly.
